name: personalFitApp
description: App para buscar e contratar personais fitness
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Gerenciamento de estado
  flutter_riverpod: ^2.4.9
  
  # Requisições HTTP
  dio: ^5.4.0
  http: ^1.1.0
  
  # UI Components
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0
  
  # UI/UX Libraries
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  flutter_slidable: ^3.0.1
  pull_to_refresh: ^2.0.0
  flutter_rating_bar: ^4.0.1
  confetti: ^0.7.0
  
  # Utilitários
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true 